### ISSUE TITLE
Something about the image feature

### ISSUE THREAD

**Issue by BruceW91** [JunweiLiang/DualAttentionNetwork#2]

**Comment by BruceW91** [comment]
Hello, Doc Liang. I try to run your DAN code. But when I run the ‘extract.py’ program, I encounter some unsolved problem. Can you release a link to download the extracted resnet-152 image features directly? Thank you very much.

**Comment by JunweiLiang** [comment]
Please provide detail descriptions of your problems. Python traceback, etc.

**Comment by BruceW91** [comment]
The error is like this
<img width="848" alt="20180824223550" src="https://user-images.githubusercontent.com/28893002/44590597-13bcde80-a7ee-11e8-9ba8-a6e744a152e4.png">

**Comment by JunweiLiang** [comment]
Looks like your model file is corrupted. run "sha256sum ImageNet-ResNet152.npz" to see whether it matches http://models.tensorpack.com/ResNet/ImageNet-ResNet152.npz.sha256

**Comment by BruceW91** [comment]
I have checked the content you suggested to check, and find they are totally matched.

**Comment by JunweiLiang** [comment]
It works fine on my machines:

python 2.7.6
>>> np.__version__
'1.14.3'
>>> tf.__version__
'1.5.1'

**Comment by BruceW91** [comment]
Ok, I will try. Could you also provide the version number of CUDA ang CUDNN? Thanks.
